### ISSUE TITLE
talend aatams_acoustic_reporting failing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#116]
```
dw_aatams_acoustic
...
Exception in component tPostgresqlInput_11
org.postgresql.util.PSQLException: ERROR: column "id" does not exist
```

is this your harvester @xhoenner ?

**Comment by xhoenner** [comment]
yes yes Laurent, no panic, that's why there was a VIT on the board.

**Comment by lbesnard** [comment]
it's blocking my 6pack !

**Comment by xhoenner** [comment]
I know, but this is not the only harvester blocking you

![screen shot 2015-07-06 at 12 36 52 pm](https://cloud.githubusercontent.com/assets/3443821/8514891/ecbd4106-23db-11e5-8b0a-6e7f7e05e671.jpg)

BTW I've got ownership over some of that 6 pack as I've been busy getting the developers to fix that issue since last iteration.
