### ISSUE TITLE
AATAMS  Delayed mode data - multi WFS spatial extent configuration

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#145]
### To reproduce
Add IMOS - AATAMS Facility - Satellite Relay Tagging Program - Delayed mode data to `https://imos.aodn.org.au/imos123/home`
Draw a bounding box over some data on step 2
Proceed to step 3

### What will happen:
Bounding box should be shown to be applied, as all the WFS layers should be able to handle filtering on the geometry column - or none of the WFS layers should be able to geometry filtering and the collection should not show that the global spatial filter is applying.

##### Next:
Download Summary Statistics as CSV and open the file.

### What does happen:
The downloaded file is not ascii text. The portal code server side code has recieved an error from Geoserver.
 (download as python and in that file you will be able to see the request that is sent to geoserver)

Eg: 
```
http://geoserver-rc.aodn.org.au/geoserver/ows?typeName=aatams_sattag_dm_summary_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((85.869140625%20-45.66015625%2C85.869140625%20-37.92578125%2C92.548828125%20-37.92578125%2C92.548828125%20-45.66015625%2C85.869140625%20-45.66015625)))
```
### What should Happen
All multi WFS layers must have spatial filtering or no multi WFS must have spatial filtering

**Comment by xhoenner** [comment]
Thanks @pmbohm for reporting this, I had noticed this happening not just with the bounding box but also with the time filters as some WFS have a single column named 'timestamp' while others have 'timestamp_start' and 'timestamp_end'.

A quick fix for this would be to rename all WFS that have a column 'timestamp_start' to 'timestamp'. Removing the bounding box filter from all WFS layers because a single WFS (summary statistics) doesn't have a geometry column is not an option. I could generate an approximation location for each entry in the  summary statistics table, but the best way to look at this issue is to address https://github.com/aodn/backlog/issues/226

**Comment by pmbohm** [comment]
From @pblain: "We can't accept data collections without a geometry filter because the spatial subset is above the accordion. The new monitor should be extended to identify configuration errors."

**Comment by xhoenner** [comment]
@smancini are you then happy if I implement the solution I outlined above? *i.e.*:
* Rename all WFS that have a column 'timestamp_start' to 'timestamp'.
* Generate an approximation location for each entry in the summary statistics table.

These changes will have to be applied to all data collections relying on SMRU data, *i.e.* AATAMS_SATTAG_DM, AODN_NT_SATTAG_OLIVERIDLEY, and HAWKSBILL_TURTLES_NT.

**Comment by xhoenner** [comment]
These are now all functional, however, I'm going to need the help of the developers to improve the SQL query used to create the summary_data views for these three data collections. 

```sql
SELECT * FROM aatams_sattag_dm_summary_data LIMIT 10;
```
returns data in less than 1 sec, but add a where clause in and it takes ages to returns 10 rows.

**Comment by pmbohm** [comment]
I'll take a look
