### ISSUE TITLE
anfog_rt harvester failing

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#187]
a file harvested by the anfog_rt harvester has been removed form the filesystem on 10-nsp-mel, whithout warning. This file was located in/mnt/archive/eMII/TALEND_harvester/ANFOG.

**Comment by danfruehauf** [comment]
`/mnt/archive` was not mounted after I rebooted 10-nsp-mel.

This mount is being mounted manually after reboot due to the fact that it can significantly slow down the startup of the machine of the remove data centre is down (in this case TPAC/Hobart).

Either way, it's up now, lets see what happens next.

**Comment by danfruehauf** [comment]
@bpasquer You can't see it (it's on chef-private), but now all of those mounts will be automatic, so the next I reboot servers, they should be there.

On the other hand, if a data centre is down, we might be less happy. Ideally those mounts will be eradicated once we're fully on AWS.

**Comment by bpasquer** [comment]
@danfruehauf I have one more request. Could you re-set the rsync between ANFOG/realtime/ on 10-aws and ANFOG/realtime/ on 10nsp. Mission Portland20160128 is the only one rsync'ed right now. Thanks

**Comment by danfruehauf** [comment]
Done.

**Comment by bpasquer** [comment]
:+1:
