### ISSUE TITLE
Nagios reporting incorrect alarm on incoming ACORN

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#202]
![nagios_10-aws_incoming-acorn](https://cloud.githubusercontent.com/assets/3498686/15307580/d3a4850a-1c17-11e6-8fb9-2a4ac379227a.png)

Nagios says incoming directory has 21 files while the file system doesn't show any...

**Comment by ggalibert** [comment]
![screenshot from 2016-05-17 10 36 47](https://cloud.githubusercontent.com/assets/3498686/15307944/78bc0a10-1c1b-11e6-8cf6-fbd01640efcb.png)

1- I wonder where these files come from (rsync?) and if we can/should leave them there.
2- If they're fine how to tell Nagios to ignore them?

**Comment by bhasin85** [comment]
Based on our investigation, it looks like these files were left by some process (Celery, Cron, Manual) either because of some error or they were of wrong format (files are not netcdf). 

It is hard to say which process created these files without any monitoring. I have zipped and moved the files as shown below. If this happens again in future we can do the monitoring using inotify or something similar to track down who (ftp, rsync, some other job) is writing these files.   

I believe Nagios is doing the right thing by alerting about these files which are not getting used. 

![200](https://cloud.githubusercontent.com/assets/2552378/15525167/f804b5c4-226a-11e6-8221-b401f7cea4d7.png)

**Comment by ggalibert** [comment]
Thanks @bhasin85

**Comment by ggalibert** [comment]
Same issue re-happening right now.

Can we find a way that these files are not left there by any process? I believe might be some rsync ghosts files...

**Comment by ggalibert** [comment]
Issue coming up again. Leaving the files there for investigation. May come from rsync. See old issue https://github.com/aodn/content/issues/53.

**Comment by ggalibert** [comment]
One year later, still the same issue is polluting Nagios reporting.

``` bash
ggalibert@10-aws-syd:/mnt/ebs/incoming/ACORN/any$ ls -la
total 772
drwxrwsr-x 2 ftp            users 741376 May 23 10:40 .
dr-xrwsr-x 4 ftp            users   4096 Apr  7 10:14 ..
-rw------- 1 projectofficer users    255 Nov 15  2016 .2JcXQK
-rw------- 1 projectofficer users    255 May 19 16:29 .aXgi7g
-rw------- 1 projectofficer users    255 Dec 26 06:12 .bJXkvX
-rw------- 1 projectofficer users    255 Jan  7 06:12 .DxrdB4
-rw------- 1 projectofficer users    255 Jan 28 04:12 .J6pN_t
-rw------- 1 projectofficer users    255 Jan 17 03:16 .jX8Qys
-rw------- 1 projectofficer users    255 Apr 24 10:01 .l_mEjJ
-rw------- 1 projectofficer users    255 Dec 16 23:59 .NJyuwE
-rw------- 1 projectofficer users    255 Feb 13 05:02 .vEmnjU
-rw------- 1 projectofficer users    255 Jan 29 04:04 .ZwEw2M
```

**Comment by ggalibert** [comment]
```CRITICAL: Directory '/mnt/ebs/incoming/ACORN/any' has '10' files ```

**Comment by ggalibert** [comment]
Issue coming up again. Every month or so I get a false alarm from Nagios and need to clean manually this directory. Is it possible that Nagios ignores these files? @pblain @lwgordonimos ?

**Comment by pblain** [comment]
I'll assign this to myself to make sure it gets looked at. I assume it can wait until next iteration.

**Comment by gsatimos** [comment]
@ggalibert did you happen to take a screenshot of this most recent occurrence of the issue? 

Just wondering because knowing some of the offending file names would be useful when examining logs for evidence of which process is leaving these files lying around (and we don't have logs going back far enough to cover the last screenshot)

**Comment by ggalibert** [comment]
@gsatimos Unfortunately no. Can do next time the issue comes back though.

**Comment by gsatimos** [comment]
cool, thank you. Hopefully I'm going to solve the problem so that time might not come :)

**Comment by lwgordonimos** [comment]
@gsatimos note that the dot files are explicitly ignored with *no* log entry recording it.

https://github.com/aodn/chef/blob/d62047670fccbaeb6ff526eb25e0f1fe13ef6b27/cookbooks/imos_po/templates/default/watch-exec-wrapper.sh.erb#L26

The only place that could potentially record it would be the FTP logs, but if it is a internal "temp file" thing, it may not even be there with the same name (since it probably creates the file as a temp name, and renames it to the final name at the end).

The FTP logs only give us this type of thing for uploads:

```bash
Sun Feb 11 13:34:40 2018 [pid 6852] CONNECT: Client "130.95.29.7"
Sun Feb 11 13:34:40 2018 [pid 6854] CONNECT: Client "130.95.29.7"
Sun Feb 11 13:34:40 2018 [pid 6851] [acornftp] OK LOGIN: Client "130.95.29.7"
Sun Feb 11 13:34:40 2018 [pid 6853] [acornftp] OK LOGIN: Client "130.95.29.7"
Sun Feb 11 13:34:41 2018 [pid 6855] [acornftp] OK UPLOAD: Client "130.95.29.7", "/any/IMOS_ACORN_RV_20180211T022500Z_CSP_FV00_radial.nc", 250796 bytes, 744.76Kbyte/sec
Sun Feb 11 13:34:41 2018 [pid 6856] [acornftp] OK UPLOAD: Client "130.95.29.7", "/any/IMOS_ACORN_RV_20180211T022500Z_FRE_FV00_radial.nc", 255218 bytes, 724.20Kbyte/sec
```

You could try to upload some things to RC and deliberately interrupt the connection to replicate it. This is why it is unsolved, because there is so little information to determine how these things got there. The files did have a NetCDF header, so it looked to me like they were legitimate upload attempts that were interrupted for some reason (could be anything between the client and server, not necessarily on our end.).

As I think I mentioned yesterday, they would most likely come from FTP than RSYNC, since a) ACORN uses FTP and b) they don't match the RSYNC naming scheme.

**Comment by gsatimos** [comment]
I think we'll spend less time on further investigation of this issue if we do it on the next occasion of it happening, and we have one of these .xxxxxx files in-situ on the filesystem.

@pblain does that sound alright? otherwise I can keep on it

@ggalibert , yes as you suggested before, if you could let me know when one of these files appears again (and you can leave it on there) that would be great

**Comment by pblain** [comment]
>  do it on the next occasion of it happening

Sounds good @gsatimos

**Comment by pblain** [comment]
Reopen if/when it reoccurs
