### ISSUE TITLE
ACORN files processed by 1-nsp not being sent to incoming on 10-aws

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#204]
![screenshot from 2016-05-25 14 30 41](https://cloud.githubusercontent.com/assets/3498686/15528229/4a46f3c8-2285-11e6-8bae-9b19ca9b87be.png)

As I was telling you @anguss00 1-nsp role is to receive data files from ACORN stations and convert them in real time into NetCDF files via Arnstein's SSR. They are then moved to out/ directory before being sent to incoming.

It looks like NetCDF files are still being created successfully but stay in the out/ directory. ACORN data is not flowing to the portal in real time any more so this is a major issue.

Unfortunately I have no idea which repo Dan set this pipeline from on 1-nsp. 

I wonder if there might have been a change in firewall/allowed ips on 10-aws incoming.

**Comment by anguss00** [comment]
I believe you're correct @ggalibert. Ssh port is not responding from 1-nsp to 10-aws. I assume ssh is how files are transferred from 1-nsp to incoming?

**Comment by ggalibert** [comment]
Knowing Dan that would be via rsync, so yes ssh.

**Comment by anguss00** [comment]
Gotcha, thanks. So definitely looks like a firewall issue.

**Comment by anguss00** [comment]
Sorry @ggalibert, where is the out directory on 1-nsp-mel?

**Comment by lwgordonimos** [comment]
This is fixed now... my fault. Our Nagios was complaining about permissions so I "corrected" it as per the alert however this other check is clearly not correct in this scenario. The check is to ensure that the FTP root folders are *not* user writable, which implies that files should be created in subfolders.

Because this has a separate FTP root directly into the "any" subfolder, this has now become an FTP root itself, and so the check is flagging it as "wrong permissions"(which is technically correct).

root@10-aws-syd:/etc/vsftpd/vusers# ls -l acornftp
lrwxrwxrwx 1 root root 21 May 17 16:08 acornftp -> /etc/vsftpd/ACORN_any
#
root@10-aws-syd:/mnt/ebs/incoming/ACORN# cat /etc/vsftpd/ACORN_any
write_enable=YES
anon_mkdir_write_enable=YES
anon_other_write_enable=YES
anon_upload_enable=YES
local_root=/mnt/ebs/incoming/ACORN/any
chroot_local_user=YES
dirlist_enable=YES
download_enable=YES
guest_username=ftp

Might need to look at the reasoning behind this setup... the "no writing in the root folder" was done for security reasons I believe... any reason it couldn't be made to work out of something like "/mnt/ebs/incoming/ACORN/any/IN" to maintain this convention?



On 25/05/16 14:36, Guillaume Galibert wrote:

[screenshot from 2016-05-25 14 30 41]<https://cloud.githubusercontent.com/assets/3498686/15528229/4a46f3c8-2285-11e6-8bae-9b19ca9b87be.png>

As I was telling you @anguss00<https://github.com/anguss00> 1-nsp role is to receive data files from ACORN stations and convert them in real time into NetCDF files via Arnstein's SSR. They are then moved to out/ directory before being sent to incoming.

It looks like NetCDF files are still being created successfully but stay in the out/ directory. ACORN data is not flowing to the portal in real time any more so this is a major issue.

Unfortunately I have no idea which repo Dan set this pipeline from on 1-nsp.

I wonder if there might have been a change in firewall/allowed ips on 10-aws incoming.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/aodn/content/issues/204>



University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by ggalibert** [comment]
@anguss00 out/ directories are on /mnt/ebs/acorn/stations/*/out .

Thanks @lwgordonimos for fixing this. For information 1-nsp doesn't use acornftp to upload files to incoming and I could not find which credentials it is using. If this is a problem for acornftp too then we could modify acornftp.json to map towards ACORN/ only instead of ACORN/any.

> the "no writing in the root folder" was done for security reasons I believe... 

Why?

**Comment by lwgordonimos** [comment]
Hmm... I can't actually see any log entries for FTP uploads to that directory at all, so you might be right about rsync... The strange thing however was that the incoming NetCDF files were owned by the ftp user, so I'm a bit confused.

Re the security: it's only for FTP since it chroots the user into a directory. It's just a best practice thing to prevent a few potential ways to "break out" of the jail.
