### ISSUE TITLE
po_s3_del does not succeed.

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#220]
Impossible de remove an object from s3 :

```
po_s3_del IMOS/SRS/OC/gridded/aqua/1d/2015/02/A20150214.aust.chl_oc3.nc
less /mnt/ebs/log/data-services/MANUAL_COMMAND_projectofficer/A20150214.aust.chl_oc3.nc..log

...
Exception in component iNetCDFInput_1
java.io.FileNotFoundException: /tmp/d20160705-13950-1tuyb5r/IMOS/SRS/OC/gridded/aqua/1d/2015/02/A20150214.aust.chl_oc3.nc (No such file or directory)
        at java.io.RandomAccessFile.open(Native Method)

```

**Comment by jonescc** [comment]
@lbesnard, po_s3_del is failing when the srs_oc harvester tries to unindex the file.

The harvester, is using the custom query option on iNewOrModifiedFileList to identify which files are new or modified, but the query used is based on pre-manifest harvesting logic and is considering the file to have been added rather than deleted causing it to fallover when trying to read the file.

You could update the custom query to correct identify when files have been added or deleted, or as discussed yesterday, remove the use of the custom query option in favor of the more generic options for reading time variables now available.

**Comment by jonescc** [comment]
Other harvesters using this option

Harvester | Comments
--- | --- 
ANMN_NRS_DAR_YON_TS  | requires changes - looks like it could use the much safer filter option which uses the provided value in a like clause against the url
ARGO | OK - based on manifest harvesting logic 
ANMN_WAVE |  requires changes - looks like it could also use the much safer filter option
AUV_VIEWER_TRACKS | requires changes - looks like it could also use the much safer filter option
FAIMMS |  requires changes - looks like it could also use the much safer filter option

I'd recommend not using the custom query option as any harvesters that use it will need to be changed if the underlying file processing is changed as it did when we moved to manifest processing.

**Comment by lbesnard** [comment]
This pr https://github.com/aodn/harvesters/tree/fixFilteringOption should fix it
