### ISSUE TITLE
robot.txt in data.aodn.org.au

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#246]
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/

what is this new file called robot.txt on the root of the bucket ? it's not in content.aodn.org.au ?

@lwgordonimos  ?

**Comment by lwgordonimos** [comment]
@lbesnard See http://www.robotstxt.org/robotstxt.html

After enabling more detailed logging, we noticed that the bucket was being crawled by web crawlers (in particular Baidu spider). 

This is not at all useful, as we don't really want data files to end up directly in search engine results. The main reason though, is that they actually download the netcdf files, which is a) pointless for us and more importantly b) costs us $$$ for bandwidth!

The robots.txt is a standard way to instruct web crawlers *not* to index the site. content.aodn.org.au is less of a problem because of the lower volume of data, but we should really put this in any web enabled bucket that we don't want to be indexed directly by search engines.
