### ISSUE TITLE
WETLABS ECO FLNTU issues

### ISSUE THREAD

**Issue by IanDarby** [aodn/content#260]
I would be interested in some feedback from users about issues they have encountered with Wetlabs ECO
particularly the FLNTU reliability, data corruption or any issues affecting data quality data outcomes. 

Cheers

**Comment by ggalibert** [comment]
@mingfeng66 says:
>I have written some codes to QC the WQM chlorophyll data, which use 3x or 5x standard deviations to remove 5-10% of the outliers in a burst measurement, which is an effective way to derive the burst mean. We may treat the 60-second measurements as a sampling process with normal or log-normal distribution, not as a time series.

**Comment by ggalibert** [comment]
@mrbeck85 says:
>@mingfeng66 - is this code posted somewhere on Github? I'd be interested to see it. Thanks!

**Comment by ggalibert** [comment]
@dirkslawinski says:
>@mrbeck85 this should be just an adjustment to the code that is already in the toolbox. Best bet would be to get @ggalibert to comment on adding it in.

**Comment by ggalibert** [comment]
@smancini says:
>The code used to generate the burst averaged product is available here https://github.com/aodn/data-services/tree/master/ANMN/burst_averaged_product

**Comment by ggalibert** [comment]
@mingfeng66 and @mrbeck85, there is already a similar test implemented in the toolbox. See [imosRateOfChangeQC](https://github.com/aodn/imos-toolbox/wiki/QCProcedures#rate-of-change-test---imosrateofchangeqc---optional) test. This test is inspired from the Argo test and follows EuroGOOS recommendations. By default, the gradient observed from 3 consecutive measurements is compared to 2 times the standard deviation observed on the first month of 'Good' data so far (this test should be in position 5 if added to the default set).

This kind of test has important imperfections that doesn't make it suitable for an automated use. Therefore, it has been decided to leave it optional so that an experienced user only would use/validate it with full knowledge.

Challenges for this kind of test are:
* Time is not taken into account. 15 minutes usually elapse between bursts of 1 minute sampling @1Hz so there can be a natural jump in variation between two bursts that cannot be compared to the variation seen within the burst.
* Using some numbers of standard deviation to remove outliers is controversial or needs expertise and time to set the correct threshold so that actual good data is left good while all bad data are flagged bad. Often, it is quicker to manually flag the data.
* Chlorophyll data derived from fluorescence often has an important variability. This variability is not necessarily noise or bad data but is due to the nature of an optical sensor. Sometimes it sees nothing, the next second it sees a chlorophyll particle, the next one nothing again, etc... Mark Baird from CSIRO (Hobart) had demonstrated in the QC summit that this variability is directly linked to the size of the observed particles.
* WQMs unfortunately seem to be quite prone to really bad data spikes no matter which parameter we're looking at.

See below plots of PH100-1106 WQM SN142 @15.5m as an illustration:
![ph100-1106_wqm-sn-142 15 5m](https://cloud.githubusercontent.com/assets/3498686/22409744/08fcdf04-e6e3-11e6-90b5-cbab57b03a25.png)
And below a zoom on the bursts just when the chlorophyll signal starts to show more variability:
![ph100-1106_wqm-sn-142 15 5m_zoom](https://cloud.githubusercontent.com/assets/3498686/22409817/2504aadc-e6e4-11e6-94bd-1055de9fabff.png)

**Comment by ggalibert** [comment]
Zoom on the first 2 bursts that show higher variability:
![ph100-1106_wqm-sn-142 15 5m_zoom_bursts](https://cloud.githubusercontent.com/assets/3498686/22409876/cc3cdb4e-e6e4-11e6-848e-eff152d3a730.png)

**Comment by ggalibert** [comment]
@IanDarby I realised this issue is in the wrong repo, so I will move it to the correct one in https://github.com/aodn/anmn-internal-discussions/issues/21
