### ISSUE TITLE
thredds internal error : SOOP XBT 

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#306]
http://thredds.aodn.org.au/thredds/catalog/IMOS/SOOP/SOOP-XBT/REALTIME/catalog.html

HTTP Status 500 - Internal Server Error

Status 500 - Internal Server Error
THREDDS Data Server Version 4.6 -- Documentation

@lwgordonimos

**Comment by lwgordonimos** [comment]
The problem identified by the logs is:

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Key 'IMOS/SOOP/SOOP-XBT/REALTIME//' contains consecutive delimiters.
```
The issue is that the pipeline looks to have erroneously uploaded temp files to the bucket, including a key named "/", hence the 'consecutive delimiters' error. Looks like a handler bug to me.

http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/SOOP/SOOP-XBT/REALTIME//tmp/tmp.QesUKsPl8y/

We need to establish whether it is safe to delete this "IMOS/SOOP/SOOP-XBT/REALTIME//" prefix (i.e. whether the data was uploaded correctly) and then delete it, and the catalogue will start working again!

**Comment by lbesnard** [comment]
will see with @smancini but I'm pretty sure this tmp folder can be deleted. It's from 2015

**Comment by smancini** [comment]
Yes I confirm, this folder can be deleted.

**Comment by lwgordonimos** [comment]
Junk files deleted, THREDDS no longer shows error.
