### ISSUE TITLE
AUV download fails

### ISSUE THREAD

**Issue by jonescc** [aodn/content#325]
### To reproduce 

* Add AUV collection to step 2 in portal https://portal.aodn.org.au/search?uuid=af5d0ff9-bb9c-4b7c-a63c-854a630b6984
* Select Colored Dissolved Organic Matter (CDOM)
* Go to step 3 and try to download Physical data CSV

### What happens

Nothing - in logs get a failed request error

### What I expect to happen

Either get a download or this option is not available

**Comment by jonescc** [comment]
Looks like there is no CDOM_b filter for auv.auv_trajectory_st_data correspoinding to the filter on auv.auv_trajectory_map

**Comment by lbesnard** [comment]
This was due to the fact that we were expecting a multi WFS when the harvester got created (a long time ago).
Some booelans were matching auv_trajectory_st_data, while others were matchin auv_trajectory_b_data
I think we ended up giving up on the multi WFS feature and only put the auv_trajectory_st_data WFS layer on the metadata record.

I am going to remove the unused booleans from the WMS

**Comment by lbesnard** [comment]
https://github.com/aodn/harvesters/pull/630

**Comment by jonescc** [comment]
Resolved by aodn/harvesters#630
