### ISSUE TITLE
Layer Testing - marvl3_atlas_tempn_map GetMap requests still occasionally timing out

### ISSUE THREAD

**Issue by pblain** [aodn/content#349]
See https://github.com/aodn/issues/issues/240

Putting it here because we need to prevent this sort of thing from happening again. e.g. Stress testing layers before pushing to prod. The new stacks _should_ make this easy. Let me know when the next layer is ready for dev/testing and we'll try it out.

**Comment by smancini** [comment]
@pblain and @jonescc What is your expectation on this issue?
We have not updated this layer for a few years now.

**Comment by jonescc** [comment]
When we moved to elastic load balancer the timeout for requests changed from 5 minutes to 1 minute.
1 minute is still an excessive amount of time for any realtime web service request.

Would be good if we looked at improving the performance of this layer so that it returned within this timelimit and preferably well within this time limit.

I can't remember the details here, but there are a few things that could possibly be looked at to do this:

* improving the performance of the query that is used to source the derails used to draw the layer from the database
* reducing the number of features that need to be drawn
* reducing the computational effort required to render the features (i.e by using a style that can be easily rendered - a dot is far easier to draw than a picture of a boat for each feature for example).

**Comment by jonescc** [comment]
Also refer https://connect.boundlessgeo.com/docs/suite/4.8/sysadmin/production/performance.html#vector-data

**Comment by jonescc** [comment]
So had a quick look at this to see what may work for this layer.  I think the main issue here is the amount of data selected for rendering in geoserver.  The data is divided up into spatial and temporal cubes including depth.  Without filtering this can result in geoserver trying to render 184317 features.   This includes rendering every depth measurement on top of every other one which probably doesn't make sense.  If I select only the top most depth cube for rendering I get 37993 features to draw (still quite a lot).

The rendering time for the style used can make a difference depending on the bbox selected.  When tested locally using just a point, the time taken varied from little difference to almost double.

So adjusting the style may help reduce the time required quite significantly in some cases, following the guidance provided above - simple styling for low level zoom/more complex styling for higher level zoom.

Might be worth looking at geoserver's DEPTH dimension functionality which defaults to rendering a particular depth rather than all (probably require changes to the portal to handle the DEPTH dimension).

Another option may be to use a coarser data cube for lower levels of zoom.

**Comment by jonescc** [comment]
Probably should mention that Pete wasn't a fan of the last option because the online resource checker doesn't test different zoom levels.  However, this is one of the recommended approaches for improving layer rendering performance in this situation.  We should just work out how to test it properly.
