### ISSUE TITLE
Portal help pages still referencing old acronyms

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#363]
Not sure whether this issue belongs to this repository, found a few of those inconsistencies the other day.

* eMII: [https://help.aodn.org.au/?s=emii](https://help.aodn.org.au/?s=emii)
* URL to the Acoustic tagging database needs to be updated on the search page result for [https://help.aodn.org.au/?s=aatams](https://help.aodn.org.au/?s=aatams), as currently pointing to [https://aatams.emii.org.au/aatams/](https://aatams.emii.org.au/aatams/). Plus AATAMS is still mentioned on the same page.

**Comment by kereid** [comment]
@xhoenner that's actually an issue with wordpress because those pages don't exist anymore yet unfortunately wordpress still finds them - been in the backlog since September 2016 https://github.com/aodn/backlog/issues/442. Not a high priority as when you click to go to the page it takes you to the correct page.  I've added a link to this issue in the backlog item.

**Comment by xhoenner** [comment]
Aha! So much stuff everywhere that's it's hard to keep track of what's already been listed or not :sweat:. Thanks Kate, I'll close this issue then.
