### ISSUE TITLE
ANMN - No mention to temperature time series

### ISSUE THREAD

**Issue by ocehugo** [aodn/content#366]
Following my perambulations along the names and the opendap in #365...

1. Although searching for temperature in the portal return the "ANMN current velocity" catalog, there is no mention in step 1 of "temperature" - the ADCP temperature sensor, within the "cog" icon.

2. The opendap pathway to name to "ANMN current velocity" is misleading:

```
http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/SA/SAM5CB/Velocity/IMOS_ANMN-SA_AETVZ_20091006T044152Z_SAM5CB_FV01_SAM5CB-0910-Sentinel-or-Monitor-Workhorse-ADCP-92.6_END-20100427T032152Z_C-20160417T160740Z.nc
```

Clearly the file hold not only "Velocity" data, but also the ADCP temperature and pressure. I think maybe a better name is "ADCP" or "ADCP Timeseries", like "CTD Timeseries"?

This allow a "no guess" behaviour: We just need a name generic enough to encompass the content of the file as done in the others.

**Comment by ggalibert** [comment]
> Although searching for temperature in the portal return the "ANMN current velocity" catalog, there is no mention in step 1 of "temperature" - the ADCP temperature sensor, within the "cog" icon.

You mean via the keywords text search. This is because the text search is reading everything in the metadata records and that the ADCP metadata record (being part of a mooring with other temperature sensors) mentions temperature.

Next to the "cog" icon are only listed parameters that are listed in the `Data Parameters` section of the metadata record. This list is the one used in the faceted search. The reason why it doesn't list temperature is because the temperature sensors on the ANMN ADCPs are not being routinely calibrated and hence their measurements are not accurate and the data provider asked us not to advertise them to the wide public or at least not include them in the temperature collection.

> The opendap pathway to name to "ANMN current velocity" is misleading [...] I think maybe a better name is "ADCP" or "ADCP Timeseries"

This is because there is not only ADCP instruments files there but also current metre ones so velocity sounded a bit more accurate.
