### ISSUE TITLE
ANFOG DM duplicates

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#376]
The following deployments are present twice:

```sql
select deployment_name, count(*) from anfog_dm.anfog_dm_trajectory_map
group by deployment_name
having count(*)>1
```

deployment_name | count(*)
-- | --
Lizard20170110 | 2
Kimberley20130214 | 2
Bicheno20100813 | 2
CrowdyHead20100809 | 2
Ningaloo20100906 | 2

**Comment by bpasquer** [comment]
Duplicates for Kimberley20130214, Bicheno20100813, CrowdyHead20100809, Ningaloo20100906 should have been manually deleted upon reception of the updated file. The command for the manual deletion has been executed today.

**Comment by bpasquer** [comment]
Issue for Lizard20170110 is similar to https://github.com/aodn/content/issues/294. The file
IMOS/ANFOG/seaglider/Lizard20170110/IMOS_ANFOG_BCEOPSTUV_20170109T100117Z_SG540_FV01_timeseries_END-20170131T204838Z.nc
has been indexed in the database, but not pushed to S3. This is due to the failure of the Talend iUpdateSpatialExtent job.
see
 /mnt/ebs/log/data-services/ANFOG_DM/IMOS_ANFOG_BCEOPSTUV_20170109T100117Z_SG540_FV01_timeseries_END-20170131T204838Z.nc.EoYyq3.20170315-094220.log.1
for further details.
we probably need to manually delete this entry form the database @lwgordonimos ?

**Comment by bpasquer** [comment]
The duplicates have been deleted.
