### ISSUE TITLE
ANMN AM - TEMP long_name att should use spaces instead of underscores

### ISSUE THREAD

**Issue by ocehugo** [aodn/content#386]
AM files are inconsistent in the sense that we got:

```
TEMP 
long_name = sea_surface_temperature
standard_name = sea_surface_temperature
```

but

```
PSAL
long_name = sea surface salinity
standard_name = sea_surface_salinity
```

The problem: In PSAL spaces(underscores) are used for long_name(standard_name) attributes. 

Blame files: *all files* in /AM/ therddds folder

**Comment by mhidas** [comment]
Actually by default we generally set the long_name to the same as standard_name (with underscores), if the latter exists. And even for those that don't have a standard_name, we often chose CF-like long_names that look similar, also w ith underscores (see e.g. the [variable attributes written by the Matlab toolbox](https://github.com/aodn/imos-toolbox/blob/master/IMOS/imosParameters.txt)).

Also, long names are not meant to be standardised (otherwise they'd be standard_name!), so we've never imposed any constraints on  them. Having said that, of course it's nice to have consistency, but in this case that means it's the PSAL long_names that would need updating to be consistent with the rest  of the moorings data.

I assume this is for the _delayed mode_ AM data?

**Comment by ggalibert** [comment]
> I also found that AM moorings are missing "instrument" global attribute. The keywords is also formatted very differently from other ANMN files.

Please open a new issue for this. Also, I think we can close this one.
