### ISSUE TITLE
Remove geometry column from _url layers

### ISSUE THREAD

**Issue by jonescc** [aodn/content#397]
Refer https://github.com/aodn/issues/issues/369

The following layers generate errors when creating the WMS GetCapabilities response:

acorn_hourly_avg_bonc_qc_timeseries_url
acorn_hourly_avg_newc_nonqc_timeseries_url
acorn_hourly_avg_newc_qc_timeseries_url
acorn_hourly_avg_turq_qc_timeseries_url
gsla_dm00_timeseries_url
gsla_nrt00_timeseries_url

GeoServer includes them in the WMS GetCapabilities response as they have a geometry defined, but the geometry does not contain a valid geometry with a defined SRS.  

Other gridded _url layers do not include a geometry, do not get included in the WMS GetCapabilities response and do not generate errors.  I can't see why we would need to publish these via WMS (they are visualised using ncwms abomination not GeoServer WMS) so I think we should remove the geometry columns from the layers above to make them consistent with other _url layers.

**Comment by ggalibert** [comment]
Currently, the following _url layers are found in the WMS GetCapabilities:
acorn_hourly_avg_bonc_nonqc_timeseries_url
acorn_hourly_avg_bonc_qc_timeseries_url
acorn_hourly_avg_cbg_nonqc_timeseries_url
acorn_hourly_avg_cbg_qc_timeseries_url
acorn_hourly_avg_cof_nonqc_timeseries_url
acorn_hourly_avg_cof_qc_timeseries_url
acorn_hourly_avg_newc_nonqc_timeseries_url
acorn_hourly_avg_newc_qc_timeseries_url
acorn_hourly_avg_rot_nonqc_timeseries_url
acorn_hourly_avg_rot_qc_timeseries_url
acorn_hourly_avg_sag_nonqc_timeseries_url
acorn_hourly_avg_sag_qc_timeseries_url
acorn_hourly_avg_turq_nonqc_timeseries_url
acorn_hourly_avg_turq_qc_timeseries_url
gsla_dm00_timeseries_url
gsla_nrt00_timeseries_url

If I understand well, whether they generate an error or not because of a non valid geometry/SRS, they should all consistently not include a geometry field.

**Comment by jonescc** [comment]
I can't see any reason to include them as Geoserver WMS layers.  The other 289 _url layers aren't.

**Comment by jonescc** [comment]
Make that the other 68 _url layers aren't - copied the total number of layers accidentally
