### ISSUE TITLE
STAARS climatology - no calendar 

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#430]
See http://thredds.aodn.org.au/thredds/dodsC/CSIRO/Climatology/SSTAARS/2017/AODN-product/SSTAARS_daily_fit_001.nc.html

Does it make sense that DAY_OF_YEAR doesn't have any calendar info in the global attribute?

**Comment by ggalibert** [comment]
Please read http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#calendar and let me know what you think.
The dataset's intent as a climatology is really to say "this is what the temperature is on the 1st of Jan, 2nd of Jan, etc... for any possible year between 1992 and 2016". We don't really care about the full date with a year. The variable has a unit to transform to an arbitrary date on year 2005 because the portal can only work with full dates. 2005 is the preferred arbitrary date because it is the mean year for the whole time period. For information it happens that 2005 is not a leap year so it has 365 days. Maybe `noleap` would be better suited than `none`? Not sure.
