### ISSUE TITLE
NRMN metadata records don't seem to point to correct WMS

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#511]
For [Survey metadata](http://catalogue-imos.aodn.org.au/geonetwork/srv/eng/catalog.search#/metadata/997c2e15-b345-438f-afac-49a4ac19be38) for example we can see
![Screenshot from 2022-09-28 15-16-46](https://user-images.githubusercontent.com/3498686/192693548-220f4d89-d0cd-49fd-b913-57fe965b35ec.png)
If you click on "Add service layer to map", it won't work. In reality, instead of `Survey Information` as heading, it should show `imos:ep_survey_list_public_map`. Although I'm surpised that the portal can display the WMS on step 2!!!

Looking at another dataset suck as ANFOG RT this is what has been done:
![Screenshot from 2022-09-28 15-20-14](https://user-images.githubusercontent.com/3498686/192693973-72d53b7e-1dc8-4092-bf71-ca2fda0dddda.png)

We need to check that all metadata records with WMS/WFS documented include the actual name of the layer in the description such as in the ANFOG RT case above.

**Comment by atkinsn** [comment]
This is portal configuration in metadata records in GN. In GN3 these 'add to maps' don't work. Not just NRMN, its all metadata records.
The top WMS is a better presentation and is more meaningful in GN than the presentation from the "older" metadata record for ANFOG.

**Comment by alexgleith** [comment]
This is caused by the link to WMS and WFS being HTTP links, whereas they should be HTTPS.

The HTTP links work fine when you view the page in HTTP, but if you view it in HTTPS then it won't follow them. (It doesn't allow you to view non-secure resources on a secure site.)

So, quick fix is to change the URIs to HTTPS.

And there's another issue, which is that the description of the WMS entry needs to have the layer name included.

**Comment by alexgleith** [comment]
Aha, that's the problem preventing us being able to add catalogue items to the map!

There's HTTP/HTTPS, for one thing. But the other is configuring the layer name for the WMS entries.

For the Gliders (e.g., this one http://catalogue-imos.aodn.org.au/geonetwork/srv/eng/catalog.search#/metadata/37662a66-ec3a-4ece-9db0-31930c181725) the "add to map" works for WMS. And note that it has the URL and the layer name listed, like this:

>This dataset is published in the view service (WMS) available at http://geoserver-123.aodn.org.au/geoserver/wms with layer name imos:aodn_uwa_glider_trajectory_map.

Adding to map results in:

<img width="1611" alt="image" src="https://user-images.githubusercontent.com/3445853/192696768-d18d1964-831c-480d-8678-04729ff61929.png">

So for the [reef network entry](http://catalogue-imos.aodn.org.au/geonetwork/srv/eng/catalog.search#/metadata/997c2e15-b345-438f-afac-49a4ac19be38) we should ensure we add the layer name, so that both humans and machines can actually use the WMS without guessing what layer they should be selecting.

**Comment by atkinsn** [comment]
A glitch in the XML of all the NRMN metadata records, has produced the WMS 'add service layer to map' being shown in the UI, which prevents the layer being added correctly to the map in GN. I have fixed the XML of all these records, and they now work.

**Comment by alexgleith** [comment]
Is this the correct layer now @gsatimos?

I guess there's a few layers, should we add all of them?

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/3445853/195752912-9bbc19c4-a7fe-4721-b165-c160ef0019ea.png">

**Comment by alexgleith** [comment]
Also @atkinsn can we set the layer name (or layer names) for all the WFS layers too?

Currently it's not set correctly, see: 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/3445853/195753219-2f4b33b4-9998-4058-a962-5339eb22e87a.png">

**Comment by atkinsn** [comment]
> Also @atkinsn can we set the layer name (or layer names) for all the WFS layers too?
> 
> Currently it's not set correctly, see:
> 
> <img alt="image" width="772" src="https://user-images.githubusercontent.com/3445853/195753219-2f4b33b4-9998-4058-a962-5339eb22e87a.png">

We are aware of this display issue, but no GeoNetwork work is being done until after the architecture review

**Comment by alexgleith** [comment]
Ah I see, there's the same issue for gliders

<img width="727" alt="image" src="https://user-images.githubusercontent.com/3445853/195761083-282f5e27-4cdb-4416-b075-5eea5dd379c5.png">

**Comment by gsatimos** [comment]
> Is this the correct layer now @gsatimos?

not sure I'm the person to ask on this @alexgleith . Maybe @nspool or @bpasquer?

**Comment by bpasquer** [comment]
WMS layer names have been fixed by @atkinsn. 
Fixing WFS layer name would require GN work but is not a priority.
