### ISSUE TITLE
AATAMS filtering options missing

### ISSUE THREAD

**Issue by pblain** [aodn/content#64]
![screenshot15](https://cloud.githubusercontent.com/assets/2802359/5024022/4bf8758e-6b57-11e4-86cb-523c5798becd.jpg)

**Comment by smancini** [comment]
This issue is waiting for the task "AATAMS XML export" to be performed.
Then it will be possible to download actual AATAMS detections from the portal 1-2-3 and project officers will configure this layer with appropriate filters.
It is expected that this layer will work similarly to the RLS dataset collection

**Comment by xhoenner** [comment]
Users can now filter by installation name, station name, project name, geom and when https://github.com/aodn/geoserver-config/pull/298 is merged, then they'll also be able to filter by receiver name, receiver deployment and recovery dates, receiver status and receiver activity.

Those filters will only allow users to download receiver metadata information, not actual tag detections. For the latter to happen we need https://github.com/aodn/aatams/issues/249 to be looked at.
